package com.aion.parser;

import com.aion.ast.Node;
import com.aion.ast.Node.*;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Converts an ANTLR4 parse tree into the typed AST.
 * Internal helpers are named build* / convert* to avoid clashing with
 * the public visitXxx() interface methods generated by ANTLR.
 */
public class AstBuilder extends AionParserBaseVisitor<Object> {

    private final String sourceName;

    public AstBuilder(String sourceName) { this.sourceName = sourceName; }

    private Pos pos(org.antlr.v4.runtime.Token token) {
        return new Pos(token.getLine(), token.getCharPositionInLine());
    }
    private Pos pos(org.antlr.v4.runtime.ParserRuleContext ctx) { return pos(ctx.getStart()); }

    /** Parse an integer literal that may use 0x/0b/0o prefix or '_' digit separators. */
    private long parseIntLit(String text) {
        boolean negative = text.startsWith("-");
        String s = negative ? text.substring(1) : text;
        s = s.replace("_", "");
        long value;
        if (s.startsWith("0x") || s.startsWith("0X")) {
            value = Long.parseLong(s.substring(2), 16);
        } else if (s.startsWith("0b") || s.startsWith("0B")) {
            value = Long.parseLong(s.substring(2), 2);
        } else if (s.startsWith("0o") || s.startsWith("0O")) {
            value = Long.parseLong(s.substring(2), 8);
        } else {
            value = Long.parseLong(s);
        }
        return negative ? -value : value;
    }

    private String stripQuotes(String s) {
        return s.substring(1, s.length() - 1)
                .replace("\\n", "\n").replace("\\r", "\r").replace("\\t", "\t")
                .replace("\\\"", "\"").replace("\\\\", "\\");
    }

    // ── Module ────────────────────────────────────────────────────────────────

    @Override
    public Node.Module visitModule(AionParser.ModuleContext ctx) {
        List<Node> decls = new ArrayList<>();
        for (var d : ctx.topDecl()) decls.add((Node) visit(d));
        return new Node.Module(decls, sourceName);
    }

    @Override
    public Node visitTopDecl(AionParser.TopDeclContext ctx) {
        if (ctx.importDecl() != null)  return (Node) visit(ctx.importDecl());
        if (ctx.typeDecl()   != null)  return (Node) visit(ctx.typeDecl());
        if (ctx.enumDecl()   != null)  return (Node) visit(ctx.enumDecl());
        if (ctx.constDecl()  != null)  return (Node) visit(ctx.constDecl());
        return (Node) visit(ctx.fnDecl());
    }

    @Override
    public Node visitConstDecl(AionParser.ConstDeclContext ctx) {
        return new ConstDecl(
                ctx.TYPE_IDENT().getText(),
                convertTypeRef(ctx.typeRef()),
                buildExpr(ctx.expr()),
                pos(ctx));
    }

    // ── Import ────────────────────────────────────────────────────────────────

    @Override
    public Node visitImportDecl(AionParser.ImportDeclContext ctx) {
        List<String> path = new ArrayList<>();
        for (var id : ctx.modulePath().IDENT()) path.add(id.getText());
        String alias = ctx.AS() != null ? ctx.IDENT().getText() : null;
        // Selective imports: import foo { bar, baz }  — importName rules hold the names
        List<String> names = new ArrayList<>();
        for (var n : ctx.importName()) names.add(n.getText());
        return new ImportDecl(path, alias, names, pos(ctx));
    }

    // ── Types ─────────────────────────────────────────────────────────────────

    @Override
    public Node visitRecordTypeDecl(AionParser.RecordTypeDeclContext ctx) {
        List<String> tp = convertTypeParams(ctx.typeParams());
        List<FieldDecl> fields = new ArrayList<>();
        for (var f : ctx.recordBody().fieldDecl())
            fields.add(new FieldDecl(f.IDENT().getText(), convertTypeRef(f.typeRef())));
        return new TypeDecl(ctx.TYPE_IDENT().getText(), tp, new TypeDeclBody.Record(fields), pos(ctx));
    }

    @Override
    public Node visitAliasTypeDecl(AionParser.AliasTypeDeclContext ctx) {
        List<String> tp = convertTypeParams(ctx.typeParams());
        Expr constraint = ctx.WHERE() != null ? buildExpr(ctx.expr()) : null;
        return new TypeDecl(ctx.TYPE_IDENT().getText(), tp,
                new TypeDeclBody.Alias(convertTypeRef(ctx.typeRef()), constraint), pos(ctx));
    }

    private List<String> convertTypeParams(AionParser.TypeParamsContext ctx) {
        if (ctx == null) return Collections.emptyList();
        List<String> r = new ArrayList<>();
        for (var t : ctx.TYPE_IDENT()) r.add(t.getText());
        return r;
    }

    // ── Enum ──────────────────────────────────────────────────────────────────

    @Override
    public Node visitEnumDecl(AionParser.EnumDeclContext ctx) {
        List<String> tp = convertTypeParams(ctx.typeParams());
        List<EnumVariant> variants = new ArrayList<>();
        for (var v : ctx.enumVariant()) variants.add(convertEnumVariant(v));
        return new EnumDecl(ctx.TYPE_IDENT().getText(), tp, variants, pos(ctx));
    }

    private EnumVariant convertEnumVariant(AionParser.EnumVariantContext ctx) {
        return switch (ctx) {
            case AionParser.TupleVariantContext tv -> {
                List<TypeRef> types = new ArrayList<>();
                for (var t : tv.typeRef()) types.add(convertTypeRef(t));
                yield new EnumVariant.Tuple(tv.TYPE_IDENT().getText(), types);
            }
            case AionParser.RecordVariantContext rv -> {
                List<FieldDecl> fields = new ArrayList<>();
                for (var f : rv.fieldDecl())
                    fields.add(new FieldDecl(f.IDENT().getText(), convertTypeRef(f.typeRef())));
                yield new EnumVariant.Record(rv.TYPE_IDENT().getText(), fields);
            }
            default -> throw new AionParseException("Unknown enum variant", pos(ctx));
        };
    }

    // ── Functions ─────────────────────────────────────────────────────────────

    @Override
    public Node visitFnDecl(AionParser.FnDeclContext ctx) {
        List<Annotation> anns = new ArrayList<>();
        for (var a : ctx.annotation()) anns.add(convertAnnotation(a));
        List<String> tp = convertTypeParams(ctx.typeParams());
        List<Param> params = new ArrayList<>();
        if (ctx.paramList() != null)
            for (var p : ctx.paramList().param())
                params.add(new Param(p.IDENT().getText(), convertTypeRef(p.typeRef())));
        // Named return: -> (name: Type)  vs plain: -> Type
        String namedReturn = null;
        TypeRef ret;
        var rt = ctx.returnType();
        if (rt instanceof AionParser.NamedReturnContext nr) {
            namedReturn = nr.IDENT().getText();
            ret = convertTypeRef(nr.typeRef());
        } else {
            ret = convertTypeRef(((AionParser.PlainReturnContext) rt).typeRef());
        }
        Stmt.Block body = buildBlock(ctx.block());
        return new FnDecl(anns, ctx.IDENT().getText(), tp, params, ret, namedReturn, body, pos(ctx));
    }

    private Annotation convertAnnotation(AionParser.AnnotationContext ctx) {
        if (ctx.ANN_PURE()        != null) return new Annotation.Pure();
        if (ctx.ANN_IO()          != null) return new Annotation.Io();
        if (ctx.ANN_MUT()         != null) return new Annotation.Mut();
        if (ctx.ANN_ASYNC()       != null) return new Annotation.Async();
        if (ctx.ANN_TEST()        != null) return new Annotation.Test();
        if (ctx.ANN_DEPRECATED()  != null) return new Annotation.Deprecated();
        if (ctx.ANN_TOOL()        != null) return new Annotation.Tool();
        if (ctx.ANN_TRUSTED()     != null) return new Annotation.TrustedAnn();
        if (ctx.ANN_UNTRUSTED()   != null) return new Annotation.UntrustedAnn();
        if (ctx.ANN_ON_FAIL()     != null) return new Annotation.OnFail(stripQuotes(ctx.STR_LIT().getText()));
        if (ctx.ANN_REQUIRES()    != null) return new Annotation.Requires(buildExpr(ctx.expr()));
        if (ctx.ANN_ENSURES()     != null) return new Annotation.Ensures(buildExpr(ctx.expr()));
        if (ctx.ANN_TIMEOUT()     != null) return new Annotation.Timeout(parseIntLit(ctx.INT_LIT().getText()));
        return new Annotation.Throws(convertTypeRef(ctx.typeRef()));
    }

    // ── Statements ────────────────────────────────────────────────────────────

    private Stmt.Block buildBlock(AionParser.BlockContext ctx) {
        List<Stmt> stmts = new ArrayList<>();
        for (var s : ctx.stmt()) stmts.add(buildStmt(s));
        return new Stmt.Block(stmts, pos(ctx));
    }

    private Stmt buildStmt(AionParser.StmtContext ctx) {
        if (ctx.letStmt()      != null) return buildLetStmt(ctx.letStmt());
        if (ctx.mutStmt()      != null) return buildMutStmt(ctx.mutStmt());
        if (ctx.assignStmt()   != null) return buildAssignStmt(ctx.assignStmt());
        if (ctx.returnStmt()   != null) return buildReturnStmt(ctx.returnStmt());
        if (ctx.ifStmt()       != null) return buildIfStmt(ctx.ifStmt());
        if (ctx.whileStmt()    != null) return buildWhileStmt(ctx.whileStmt());
        if (ctx.forStmt()      != null) return buildForStmt(ctx.forStmt());
        if (ctx.assertStmt()   != null) return buildAssertStmt(ctx.assertStmt());
        if (ctx.describeStmt() != null) return buildDescribeStmt(ctx.describeStmt());
        if (ctx.breakStmt()    != null) return new Stmt.Break(pos(ctx));
        if (ctx.continueStmt() != null) return new Stmt.Continue(pos(ctx));
        return new Stmt.ExprStmt(buildExpr(ctx.exprStmt().expr()), pos(ctx));
    }

    private Stmt buildAssertStmt(AionParser.AssertStmtContext ctx) {
        Expr cond = buildExpr(ctx.expr(0));
        Expr msg  = ctx.expr().size() > 1 ? buildExpr(ctx.expr(1)) : null;
        return new Stmt.Assert(cond, msg, pos(ctx));
    }

    private Stmt buildDescribeStmt(AionParser.DescribeStmtContext ctx) {
        String text = stripQuotes(ctx.STR_LIT().getText());
        return new Stmt.Describe(text, pos(ctx));
    }

    private Stmt buildLetStmt(AionParser.LetStmtContext ctx) {
        TypeRef t = ctx.typeRef() != null ? convertTypeRef(ctx.typeRef()) : null;
        return new Stmt.Let(ctx.IDENT().getText(), t, buildExpr(ctx.expr()), pos(ctx));
    }

    private Stmt buildMutStmt(AionParser.MutStmtContext ctx) {
        TypeRef t = ctx.typeRef() != null ? convertTypeRef(ctx.typeRef()) : null;
        return new Stmt.Mut(ctx.IDENT().getText(), t, buildExpr(ctx.expr()), pos(ctx));
    }

    private Stmt buildAssignStmt(AionParser.AssignStmtContext ctx) {
        AssignTarget target = buildAssignTarget(ctx.assignTarget());
        return new Stmt.Assign(target, buildExpr(ctx.expr()), pos(ctx));
    }

    private AssignTarget buildAssignTarget(AionParser.AssignTargetContext ctx) {
        if (ctx.LBRACKET() != null)
            return new AssignTarget.Index(ctx.IDENT(0).getText(), buildExpr(ctx.expr()));
        List<String> path = new ArrayList<>();
        for (var id : ctx.IDENT()) path.add(id.getText());
        return new AssignTarget.Field(path);
    }

    private Stmt buildReturnStmt(AionParser.ReturnStmtContext ctx) {
        Expr val = ctx.expr() != null ? buildExpr(ctx.expr()) : null;
        return new Stmt.Return(val, pos(ctx));
    }

    private Stmt buildIfStmt(AionParser.IfStmtContext ctx) {
        List<IfBranch> branches = new ArrayList<>();
        List<AionParser.ExprContext> conds   = ctx.expr();
        List<AionParser.BlockContext> blocks = ctx.block();
        for (int i = 0; i < conds.size(); i++)
            branches.add(new IfBranch(buildExpr(conds.get(i)), buildBlock(blocks.get(i))));
        Stmt.Block elseBlock = blocks.size() > conds.size()
                ? buildBlock(blocks.get(blocks.size() - 1)) : null;
        return new Stmt.If(branches, elseBlock, pos(ctx));
    }

    private Stmt buildWhileStmt(AionParser.WhileStmtContext ctx) {
        return new Stmt.While(buildExpr(ctx.expr()), buildBlock(ctx.block()), pos(ctx));
    }

    private Stmt buildForStmt(AionParser.ForStmtContext ctx) {
        return new Stmt.For(ctx.IDENT().getText(), buildExpr(ctx.expr()), buildBlock(ctx.block()), pos(ctx));
    }

    // ── Expressions ───────────────────────────────────────────────────────────

    private Expr buildExpr(AionParser.ExprContext ctx) {
        return switch (ctx) {
            case AionParser.ExclusiveRangeContext c ->
                new Expr.RangeLit(buildPipeExpr(c.pipeExpr(0)), buildPipeExpr(c.pipeExpr(1)), false, pos(c));
            case AionParser.InclusiveRangeContext c ->
                new Expr.RangeLit(buildPipeExpr(c.pipeExpr(0)), buildPipeExpr(c.pipeExpr(1)), true, pos(c));
            case AionParser.ExprPipeContext c ->
                buildPipeExpr(c.pipeExpr());
            default -> throw new AionParseException("Unknown expr context: " + ctx.getClass().getSimpleName(), pos(ctx));
        };
    }

    private Expr buildPipeExpr(AionParser.PipeExprContext ctx) {
        List<AionParser.LogicOrExprContext> parts = ctx.logicOrExpr();
        Expr result = buildLogicOrExpr(parts.get(0));
        for (int i = 1; i < parts.size(); i++)
            result = new Expr.Pipe(result, buildLogicOrExpr(parts.get(i)), pos(ctx));
        return result;
    }

    private Expr buildLogicOrExpr(AionParser.LogicOrExprContext ctx) {
        List<AionParser.LogicAndExprContext> parts = ctx.logicAndExpr();
        Expr result = buildLogicAndExpr(parts.get(0));
        for (int i = 1; i < parts.size(); i++)
            result = new Expr.BinOp(BinOpKind.OR, result, buildLogicAndExpr(parts.get(i)), pos(ctx));
        return result;
    }

    private Expr buildLogicAndExpr(AionParser.LogicAndExprContext ctx) {
        List<AionParser.EqualityExprContext> parts = ctx.equalityExpr();
        Expr result = buildEqualityExpr(parts.get(0));
        for (int i = 1; i < parts.size(); i++)
            result = new Expr.BinOp(BinOpKind.AND, result, buildEqualityExpr(parts.get(i)), pos(ctx));
        return result;
    }

    private Expr buildEqualityExpr(AionParser.EqualityExprContext ctx) {
        List<AionParser.RelationalExprContext> parts = ctx.relationalExpr();
        Expr result = buildRelationalExpr(parts.get(0));
        for (int i = 1; i < parts.size(); i++) {
            String op = ctx.getChild(i * 2 - 1).getText();
            result = new Expr.BinOp(op.equals("==") ? BinOpKind.EQ : BinOpKind.NEQ,
                    result, buildRelationalExpr(parts.get(i)), pos(ctx));
        }
        return result;
    }

    private Expr buildRelationalExpr(AionParser.RelationalExprContext ctx) {
        List<AionParser.AddExprContext> parts = ctx.addExpr();
        Expr result = buildAddExpr(parts.get(0));
        for (int i = 1; i < parts.size(); i++) {
            BinOpKind kind = switch (ctx.getChild(i * 2 - 1).getText()) {
                case "<"  -> BinOpKind.LT;
                case "<=" -> BinOpKind.LE;
                case ">"  -> BinOpKind.GT;
                default   -> BinOpKind.GE;
            };
            result = new Expr.BinOp(kind, result, buildAddExpr(parts.get(i)), pos(ctx));
        }
        return result;
    }

    private Expr buildAddExpr(AionParser.AddExprContext ctx) {
        List<AionParser.MulExprContext> parts = ctx.mulExpr();
        Expr result = buildMulExpr(parts.get(0));
        for (int i = 1; i < parts.size(); i++) {
            BinOpKind kind = ctx.getChild(i * 2 - 1).getText().equals("+") ? BinOpKind.ADD : BinOpKind.SUB;
            result = new Expr.BinOp(kind, result, buildMulExpr(parts.get(i)), pos(ctx));
        }
        return result;
    }

    private Expr buildMulExpr(AionParser.MulExprContext ctx) {
        List<AionParser.UnaryExprContext> parts = ctx.unaryExpr();
        Expr result = buildUnaryExpr(parts.get(0));
        for (int i = 1; i < parts.size(); i++) {
            BinOpKind kind = switch (ctx.getChild(i * 2 - 1).getText()) {
                case "*" -> BinOpKind.MUL;
                case "/" -> BinOpKind.DIV;
                default  -> BinOpKind.MOD;
            };
            result = new Expr.BinOp(kind, result, buildUnaryExpr(parts.get(i)), pos(ctx));
        }
        return result;
    }

    private Expr buildUnaryExpr(AionParser.UnaryExprContext ctx) {
        if (ctx.NOT()   != null) return new Expr.UnaryOp(UnaryOpKind.NOT, buildUnaryExpr(ctx.unaryExpr()), pos(ctx));
        if (ctx.MINUS() != null) return new Expr.UnaryOp(UnaryOpKind.NEG, buildUnaryExpr(ctx.unaryExpr()), pos(ctx));
        return buildPostfixExpr(ctx.postfixExpr());
    }

    private Expr buildPostfixExpr(AionParser.PostfixExprContext ctx) {
        Expr result = buildPrimaryExpr(ctx.primaryExpr());
        for (var pf : ctx.postfix()) {
            result = switch (pf) {
                case AionParser.FieldAccessContext fa ->
                        new Expr.FieldAccess(result, fa.IDENT().getText(), pos(fa));
                case AionParser.MethodCallContext mc ->
                        new Expr.MethodCall(result, mc.IDENT().getText(), buildArgs(mc.argList()), pos(mc));
                case AionParser.IndexAccessContext ia ->
                        new Expr.IndexAccess(result, buildExpr(ia.expr()), pos(ia));
                case AionParser.PropagateOpContext po ->
                        new Expr.Propagate(result, pos(po));
                default -> throw new AionParseException("Unknown postfix", pos(pf));
            };
        }
        return result;
    }

    private Expr buildPrimaryExpr(AionParser.PrimaryExprContext ctx) {
        return switch (ctx) {
            case AionParser.IntLitContext    c -> new Expr.IntLit(parseIntLit(c.INT_LIT().getText()), pos(c));
            case AionParser.FloatLitContext  c -> new Expr.FloatLit(Double.parseDouble(c.FLOAT_LIT().getText().replace("_", "")), pos(c));
            case AionParser.StrLitContext    c -> new Expr.StrLit(stripQuotes(c.STR_LIT().getText()), pos(c));
            case AionParser.InterpStrLitContext c -> buildInterpStr(c.INTERP_STR().getText(), pos(c));
            case AionParser.BoolTrueContext  c -> new Expr.BoolLit(true,  pos(c));
            case AionParser.BoolFalseContext c -> new Expr.BoolLit(false, pos(c));
            case AionParser.NoneLitContext   c -> new Expr.NoneLit(pos(c));
            case AionParser.SomeLitContext   c -> new Expr.SomeLit(buildExpr(c.expr()), pos(c));
            case AionParser.OkLitContext    c -> new Expr.OkLit(buildExpr(c.expr()), pos(c));
            case AionParser.ErrLitContext   c -> new Expr.ErrLit(buildExpr(c.expr()), pos(c));
            case AionParser.TrustedExprContext   c -> new Expr.TrustedExpr(buildExpr(c.expr()), pos(c));
            case AionParser.UntrustedExprContext c -> new Expr.UntrustedExpr(buildExpr(c.expr()), pos(c));
            case AionParser.VarRefContext    c -> new Expr.VarRef(c.IDENT().getText(), pos(c));
            case AionParser.EnumVariantRefContext c ->
                    new Expr.EnumVariantRef(c.TYPE_IDENT(0).getText(), c.TYPE_IDENT(1).getText(), pos(c));
            case AionParser.EnumRecordLitContext c ->
                    new Expr.EnumRecordLit(c.TYPE_IDENT(0).getText(), c.TYPE_IDENT(1).getText(),
                            buildNamedArgs(c.namedArgList()), pos(c));
            case AionParser.EnumTupleLitContext c ->
                    new Expr.EnumTupleLit(c.TYPE_IDENT(0).getText(), c.TYPE_IDENT(1).getText(),
                            buildArgs(c.argList()), pos(c));
            case AionParser.RecordLitContext c ->
                    new Expr.RecordLit(c.TYPE_IDENT().getText(), buildNamedArgs(c.namedArgList()), pos(c));
            case AionParser.FnCallContext c ->
                    new Expr.FnCall(c.IDENT().getText(), buildArgs(c.argList()), pos(c));
            // Uppercase identifiers used as values (constants, e.g. MAX, GREETING)
            case AionParser.ConstRefContext  c -> new Expr.VarRef(c.TYPE_IDENT().getText(), pos(c));
            case AionParser.ConstFnCallContext c -> new Expr.FnCall(c.TYPE_IDENT().getText(), buildArgs(c.argList()), pos(c));
            case AionParser.MatchExprRefContext  c -> buildMatchExpr(c.matchExpr());
            case AionParser.BlockExprRefContext  c -> buildBlockExpr(c.blockExpr());
            case AionParser.ListLitRefContext    c -> buildListLit(c.listLit());
            case AionParser.MapLitRefContext     c -> buildMapLit(c.mapLit());
            case AionParser.LambdaExprContext    c -> buildLambda(c);
            case AionParser.TupleLitRefContext c -> {
                List<Expr> elems = new ArrayList<>();
                for (var e : c.tupleLit().expr()) elems.add(buildExpr(e));
                yield new Expr.TupleLit(elems, pos(c));
            }
            case AionParser.ParensContext        c -> buildExpr(c.expr());
            default -> throw new AionParseException("Unknown primary", pos(ctx));
        };
    }

    private List<Arg> buildArgs(AionParser.ArgListContext ctx) {
        if (ctx == null) return Collections.emptyList();
        List<Arg> args = new ArrayList<>();
        for (var a : ctx.namedArg()) {
            args.add(switch (a) {
                case AionParser.NamedArgumentContext n ->
                        new Arg.Named(n.IDENT().getText(), buildExpr(n.expr()));
                case AionParser.PosArgumentContext p ->
                        new Arg.Positional(buildExpr(p.expr()));
                default -> throw new AionParseException("Unknown arg", pos(a));
            });
        }
        return args;
    }

    private List<NamedArg> buildNamedArgs(AionParser.NamedArgListContext ctx) {
        if (ctx == null) return Collections.emptyList();
        List<NamedArg> args = new ArrayList<>();
        for (var a : ctx.namedArg())
            if (a instanceof AionParser.NamedArgumentContext n)
                args.add(new NamedArg(n.IDENT().getText(), buildExpr(n.expr())));
        return args;
    }

    private Expr buildMatchExpr(AionParser.MatchExprContext ctx) {
        Expr subject = buildExpr(ctx.expr());
        List<MatchArm> arms = new ArrayList<>();
        for (var arm : ctx.matchArm()) {
            Pattern pat  = convertPattern(arm.pattern());
            Expr guard   = arm.IF() != null ? buildExpr(arm.expr(0)) : null;
            Expr bodyExpr = arm.IF() != null
                    ? (arm.expr().size() > 1 ? buildExpr(arm.expr(1))
                       : new Expr.BlockExpr(buildBlock(arm.block()).stmts(), new Expr.BoolLit(true, pos(arm)), pos(arm)))
                    : (arm.expr().size() > 0 ? buildExpr(arm.expr(0))
                       : new Expr.BlockExpr(buildBlock(arm.block()).stmts(), new Expr.BoolLit(true, pos(arm)), pos(arm)));
            arms.add(new MatchArm(pat, guard, bodyExpr));
        }
        return new Expr.Match(subject, arms, pos(ctx));
    }

    /** Build a lambda expression: {@code fn(x: Int, y: Int) -> Int { x + y }}. */
    private Expr buildLambda(AionParser.LambdaExprContext ctx) {
        List<Param> params = new ArrayList<>();
        if (ctx.paramList() != null)
            for (var p : ctx.paramList().param())
                params.add(new Param(p.IDENT().getText(), convertTypeRef(p.typeRef())));
        TypeRef ret   = convertTypeRef(ctx.typeRef());
        Stmt.Block body = buildBlock(ctx.block());
        return new Expr.Lambda(params, ret, body, pos(ctx));
    }

    /**
     * Parse an INTERP_STR token like {@code "Hello ${name}, score=${score}!"}
     * into an {@link Expr.InterpolatedStr} whose parts list alternates between
     * raw {@code String} segments and {@link Expr} holes.
     */
    private Expr buildInterpStr(String raw, Pos pos) {
        // raw includes surrounding quotes; strip them
        String inner = raw.substring(1, raw.length() - 1);
        List<Object> parts = new ArrayList<>();
        int i = 0;
        StringBuilder seg = new StringBuilder();
        while (i < inner.length()) {
            if (inner.startsWith("${", i)) {
                parts.add(seg.toString());
                seg.setLength(0);
                int end = inner.indexOf('}', i + 2);
                String exprSrc = inner.substring(i + 2, end);
                // Sub-parse the expression snippet
                parts.add(AionFrontend.parseExprString(exprSrc, pos.line()));
                i = end + 1;
            } else if (inner.startsWith("\\n", i)) {
                seg.append('\n'); i += 2;
            } else if (inner.startsWith("\\t", i)) {
                seg.append('\t'); i += 2;
            } else if (inner.startsWith("\\\"", i)) {
                seg.append('"'); i += 2;
            } else if (inner.startsWith("\\\\", i)) {
                seg.append('\\'); i += 2;
            } else {
                seg.append(inner.charAt(i++));
            }
        }
        parts.add(seg.toString());
        return new Expr.InterpolatedStr(parts, pos);
    }

    private Expr buildBlockExpr(AionParser.BlockExprContext ctx) {
        List<Stmt> stmts = new ArrayList<>();
        for (var s : ctx.stmt()) stmts.add(buildStmt(s));
        return new Expr.BlockExpr(stmts, buildExpr(ctx.expr()), pos(ctx));
    }

    private Expr buildListLit(AionParser.ListLitContext ctx) {
        List<Expr> elems = new ArrayList<>();
        for (var e : ctx.expr()) elems.add(buildExpr(e));
        return new Expr.ListLit(elems, pos(ctx));
    }

    private Expr buildMapLit(AionParser.MapLitContext ctx) {
        List<MapEntry> entries = new ArrayList<>();
        for (var e : ctx.mapEntry())
            entries.add(new MapEntry(buildExpr(e.expr(0)), buildExpr(e.expr(1))));
        return new Expr.MapLit(entries, pos(ctx));
    }

    // ── Patterns ─────────────────────────────────────────────────────────────

    private Pattern convertPattern(AionParser.PatternContext ctx) {
        return switch (ctx) {
            case AionParser.WildcardPatternContext  ignored -> new Pattern.Wildcard();
            case AionParser.IntPatternContext   c -> new Pattern.IntPat(parseIntLit(c.INT_LIT().getText()));
            case AionParser.FloatPatternContext c -> new Pattern.FloatPat(Double.parseDouble(c.FLOAT_LIT().getText()));
            case AionParser.StrPatternContext   c -> new Pattern.StrPat(stripQuotes(c.STR_LIT().getText()));
            case AionParser.TruePatternContext  ignored -> new Pattern.BoolPat(true);
            case AionParser.FalsePatternContext ignored -> new Pattern.BoolPat(false);
            case AionParser.NonePatternContext  ignored -> new Pattern.NonePat();
            case AionParser.SomePatternContext  c -> new Pattern.SomePat(convertPattern(c.pattern()));
            case AionParser.OkPatternContext    c -> new Pattern.OkPat(convertPattern(c.pattern()));
            case AionParser.ErrPatternContext   c -> new Pattern.ErrPat(convertPattern(c.pattern()));
            case AionParser.EnumPatternContext  c ->
                    new Pattern.EnumPat(c.TYPE_IDENT(0).getText(), c.TYPE_IDENT(1).getText());
            case AionParser.EnumTuplePatternContext c -> {
                List<Pattern> fields = new ArrayList<>();
                for (var p : c.pattern()) fields.add(convertPattern(p));
                yield new Pattern.EnumTuplePat(c.TYPE_IDENT(0).getText(), c.TYPE_IDENT(1).getText(), fields);
            }
            case AionParser.EnumRecordPatternContext c ->
                    new Pattern.EnumRecordPat(c.TYPE_IDENT(0).getText(), c.TYPE_IDENT(1).getText(),
                            buildFieldPatterns(c.fieldPattern()));
            case AionParser.RecordPatternContext c ->
                    new Pattern.RecordPat(c.TYPE_IDENT().getText(), buildFieldPatterns(c.fieldPattern()));
            case AionParser.TuplePatternContext c -> {
                List<Pattern> elems = new ArrayList<>();
                for (var p : c.pattern()) elems.add(convertPattern(p));
                yield new Pattern.TuplePat(elems);
            }
            case AionParser.BindPatternContext c -> new Pattern.Bind(c.IDENT().getText());
            default -> throw new AionParseException("Unknown pattern", pos(ctx));
        };
    }

    private List<FieldPat> buildFieldPatterns(List<AionParser.FieldPatternContext> ctxs) {
        List<FieldPat> fps = new ArrayList<>();
        for (var fp : ctxs) {
            if (fp.pattern() != null)
                fps.add(new FieldPat(fp.IDENT().getText(), convertPattern(fp.pattern())));
            else
                fps.add(new FieldPat(fp.IDENT().getText(), new Pattern.Bind(fp.IDENT().getText())));
        }
        return fps;
    }

    // ── Type references ───────────────────────────────────────────────────────

    private TypeRef convertTypeRef(AionParser.TypeRefContext ctx) {
        return switch (ctx) {
            case AionParser.IntTypeContext    ignored -> new TypeRef.IntT();
            case AionParser.FloatTypeContext  ignored -> new TypeRef.FloatT();
            case AionParser.BoolTypeContext   ignored -> new TypeRef.BoolT();
            case AionParser.StrTypeContext    ignored -> new TypeRef.StrT();
            case AionParser.UnitTypeContext   ignored -> new TypeRef.UnitT();
            case AionParser.OptionTypeContext c -> new TypeRef.OptionT(convertTypeRef(c.typeRef()));
            case AionParser.ResultTypeContext c ->
                    new TypeRef.ResultT(convertTypeRef(c.typeRef(0)), convertTypeRef(c.typeRef(1)));
            case AionParser.ListTypeContext c -> new TypeRef.ListT(convertTypeRef(c.typeRef()));
            case AionParser.MapTypeContext  c ->
                    new TypeRef.MapT(convertTypeRef(c.typeRef(0)), convertTypeRef(c.typeRef(1)));
            case AionParser.NamedTypeContext c -> {
                List<TypeRef> args = new ArrayList<>();
                for (var t : c.typeRef()) args.add(convertTypeRef(t));
                yield new TypeRef.Named(c.TYPE_IDENT().getText(), args);
            }
            case AionParser.TupleTypeContext c -> {
                List<TypeRef> elems = new ArrayList<>();
                for (var t : c.typeRef()) elems.add(convertTypeRef(t));
                yield new TypeRef.TupleT(elems);
            }
            case AionParser.FnTypeContext c -> {
                List<AionParser.TypeRefContext> all = c.typeRef();
                List<TypeRef> params = new ArrayList<>();
                for (int i = 0; i < all.size() - 1; i++) params.add(convertTypeRef(all.get(i)));
                yield new TypeRef.FnT(params, convertTypeRef(all.get(all.size() - 1)));
            }
            default -> throw new AionParseException("Unknown type ref", pos(ctx));
        };
    }
}

